' Start the Kara gateway with no console window.
'
' Paths are resolved relative to this script, so the file works from any clone
' location and survives moving the repo. It used to be regenerated by
' install_gateway.ps1 with absolute paths baked in, which meant the committed
' copy carried one machine's directory layout and was wrong everywhere else.
Option Explicit
Dim fso, sh, scriptDir, packageDir, python, runGateway, cmd

Set fso = CreateObject("Scripting.FileSystemObject")
Set sh = CreateObject("WScript.Shell")

scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
packageDir = fso.GetParentFolderName(scriptDir)

python = fso.BuildPath(packageDir, ".venv\Scripts\pythonw.exe")
If Not fso.FileExists(python) Then
    python = fso.BuildPath(packageDir, ".venv\Scripts\python.exe")
End If
runGateway = fso.BuildPath(scriptDir, "run_gateway.py")

If Not fso.FileExists(python) Then
    WScript.Echo "Kara: no interpreter at " & python & " - run 'uv sync' first."
    WScript.Quit 1
End If
If Not fso.FileExists(runGateway) Then
    WScript.Echo "Kara: run_gateway.py not found at " & runGateway
    WScript.Quit 1
End If

sh.CurrentDirectory = packageDir
cmd = """" & python & """ """ & runGateway & """"
sh.Run cmd, 0, False
