' Auto-generated by install_gateway.ps1 - re-run install after moving the repo.
Option Explicit
Dim sh, cmd
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "D:\GitHub Repos\Kara-local\personal_agent"
cmd = """D:\GitHub Repos\Kara-local\personal_agent\.venv\Scripts\python.exe"" ""D:\GitHub Repos\Kara-local\personal_agent\scripts\run_gateway.py"""
sh.Run cmd, 0, False
